boot.o: boot.S multiboot.h x86_desc.h types.h
idt_linkage.o: idt_linkage.S idt_linkage.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h keyboard.h paging.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h keyboard.h paging.h rtc.h \
  i8259.h tests.h idt_linkage.h syscall.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h keyboard.h \
  paging.h i8259.h debug.h tests.h rtc.h idt.h scheduling.h syscall.h
keyboard.o: keyboard.c idt.h x86_desc.h types.h lib.h keyboard.h paging.h \
  i8259.h tests.h scheduling.h syscall.h rtc.h
lib.o: lib.c lib.h types.h keyboard.h paging.h
paging.o: paging.c paging.h lib.h types.h keyboard.h
rtc.o: rtc.c rtc.h i8259.h types.h lib.h keyboard.h paging.h tests.h
scheduling.o: scheduling.c scheduling.h lib.h types.h keyboard.h paging.h \
  i8259.h syscall.h rtc.h tests.h idt.h x86_desc.h
syscall.o: syscall.c syscall.h rtc.h i8259.h types.h lib.h keyboard.h \
  paging.h tests.h idt.h x86_desc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h paging.h \
  rtc.h i8259.h syscall.h idt.h
